env:
  global:
    - CC_TEST_REPORTER_ID=40fd488627355e3e12fd14b84e18e1e7b8ee40d2271823ecd2427f02f4aad61d
language: ruby
services:
  - postgresql
rvm: 
  - 2.4.1
before_script:
  - psql -c 'create database capacitor_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

